DROP TABLE IF EXISTS users;
CREATE TABLE users
(
    id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(100) NOT NULL,
    age    integer,
    salary decimal
);
DROP TABLE IF EXISTS currency_rate;
CREATE TABLE currency_rate
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    success   VARCHAR(100) NOT NULL,
    timestamp VARCHAR(100) NOT NULL,
    base      VARCHAR(100) NOT NULL,
    date      VARCHAR(100) NOT NULL,
    rates     jsonb        NOT NULL
);